export const mockData = [
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },

  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
];