export const mockData = [
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },

  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
  {
    assetNo: "#DJHBJ334",
    assetName: "Company A - Windows - Laptop - 1",
    productName: "Lenovo Idea Pad - Intel Ultra 9",
    status: "Active",
  },
  {
    assetNo: "#KJNDLOW",
    assetName: "Company B - Mac - Laptop - 2",
    productName: "MacBook Air - M4",
    status: "In Active",
  },
];
export const mockAssetdata = {
  "hostname": "LTIN-APLQWLF44X35N",
  "device_name": "MacBook Pro",
  "serial_number": "QWLF44X35N",
  "mac_address": "16:c2:bc:6e:a6:fe",
  "os": "Darwin",
  "os_release": "24.5.0",
  "os_version": "Darwin Kernel Version 24.5.0",
  "architecture": "64bit",
  "machine": "arm64",
  "processor": "arm",
  "python_version": "3.9.6",
  "timestamp": "2025-07-25T09:17:48.578796+00:00",
  "physical_cpu_cores": 10,
  "logical_cpu_cores": 10,
  "avg_cpu_per_core_usage_percent": 15.0,
  "cpu_usage_percent": 15.0,
  "cpu_freq_current_mhz": 3228,
  "cpu_freq_min_mhz": 600,
  "cpu_freq_max_mhz": 3228,
  "memory_total_gb": 16.0,
  "memory_used_gb": 7.86,
  "memory_free_gb": 6.26,
  "memory_used_percent": 60.9,
  "swap_total_gb": 3.0,
  "swap_used_gb": 1.76,
  "swap_used_percent": 58.8,
  "total_disk_usage_gb": 278.19,
  "total_disk_size_gb": 2303.62,
  "total_disk_used_percent": 12.1,
  "boot_time_utc": "2025-07-23T17:27:28+00:00",
  "uptime_seconds": 143421,
  "uptime_hms": "1 day, 15:50:21",
  "battery_present": true,
  "battery_percent": 65,
  "battery_plugged_in": false,
  "battery_time_left_seconds": 27960,
  "battery_time_left_approx": "7h 46m",
  "battery_cycle_count": 541
}